apiVersion: database.oci.m.upbound.io/v1alpha1
kind: AutonomousVmClusterOrdsCertificateManagement
metadata:
  annotations:
    meta.upbound.io/example-id: database/v1alpha1/autonomousvmclusterordscertificatemanagement
  labels:
    testing.upbound.io/example-name: test_avm_ords_mgmt_res
  name: test-avm-ords-mgmt-res
  namespace: ${TARGET_NAMESPACE}
spec:
  forProvider:
    autonomousVmClusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_autonomous_vm_cluster
    certificateGenerationType: BYOC
    certificateId: ${var.avm_certificate_id}
  # providerConfig defaults to "ClusterProviderConfig"; set providerConfigRef to "ProviderConfig" to use namespaced providerConfig.
  providerConfigRef:
    name: default
    kind: ProviderConfig
