apiVersion: database.oci.m.upbound.io/v1alpha1
kind: AutonomousDatabaseRegionalWalletManagement
metadata:
  annotations:
    meta.upbound.io/example-id: database/v1alpha1/autonomousdatabaseregionalwalletmanagement
  labels:
    testing.upbound.io/example-name: test_autonomous_database_regional_wallet_management
  name: test-autonomous-database-regional-wallet-management
  namespace: ${TARGET_NAMESPACE}
spec:
  forProvider:
    shouldRotate: false
  # providerConfig defaults to "ClusterProviderConfig"; set providerConfigRef to "ProviderConfig" to use namespaced providerConfig.
  providerConfigRef:
    name: default
    kind: ProviderConfig
