apiVersion: dataflow.oci.m.upbound.io/v1alpha1
kind: SqlEndpoint
metadata:
  annotations:
    meta.upbound.io/example-id: dataflow/v1alpha1/sqlendpoint
  labels:
    testing.upbound.io/example-name: test_sql_endpoint
  name: test-sql-endpoint
  namespace: ${TARGET_NAMESPACE}
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    displayName: test_sql_endpoint
    driverShape: VM.Standard.E4.Flex
    driverShapeConfig:
      - memoryInGbs: 32
        ocpus: 2
    executorShape: VM.Standard.E4.Flex
    executorShapeConfig:
      - memoryInGbs: 32
        ocpus: 2
    freeformTags:
      Department: Finance
    maxExecutorCount: 2
    metastoreId: ${var.metastore_id}
    minExecutorCount: 1
    networkConfiguration:
      - networkType: SECURE_ACCESS
    sqlEndpointVersion: 3.2.1
  # providerConfig defaults to "ClusterProviderConfig"; set providerConfigRef to "ProviderConfig" to use namespaced providerConfig.
  providerConfigRef:
    name: default
    kind: ProviderConfig
