apiVersion: zpr.oci.m.upbound.io/v1alpha1
kind: Configuration
metadata:
  annotations:
    meta.upbound.io/example-id: zpr/v1alpha1/configuration
  labels:
    testing.upbound.io/example-name: test_configuration
  name: test-configuration
  namespace: ${TARGET_NAMESPACE}
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    definedTags: ${var.configuration_defined_tags}
    freeformTags: ${var.configuration_freeform_tags}
  # providerConfig defaults to "ClusterProviderConfig"; set providerConfigRef to "ProviderConfig" to use namespaced providerConfig.
  providerConfigRef:
    name: default
    kind: ProviderConfig
