apiVersion: budget.oci.upbound.io/v1alpha1
kind: AlertRule
metadata:
  name: alertrule1
  labels:
    testing.upbound.io/example-name: alertrule_label_1
spec:
  forProvider:
    budgetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: budget_label_1
    threshold: 90.0
    thresholdType: "PERCENTAGE"
    type: "ACTUAL"