apiVersion: devops.oci.m.upbound.io/v1alpha1
kind: DeployStage
metadata:
  annotations:
    meta.upbound.io/example-id: devops/v1alpha1/deploystage
  labels:
    testing.upbound.io/example-name: test_wait_deploy_stage
  name: test-wait-deploy-stage
  namespace: ${TARGET_NAMESPACE}
spec:
  forProvider:
    deployPipelineIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_deploy_pipeline
    deployStagePredecessorCollection:
      - items:
          - idSelector:
              matchLabels:
                testing.upbound.io/example-name: test_deploy_pipeline
    deployStageType: WAIT
    description: description
    displayName: displayName
    waitCriteria:
      - waitDuration: PT5S
        waitType: ABSOLUTE_WAIT
  # providerConfig defaults to "ClusterProviderConfig"; set providerConfigRef to "ProviderConfig" to use namespaced providerConfig.
  providerConfigRef:
    name: default
    kind: ProviderConfig
