apiVersion: devops.oci.m.upbound.io/v1alpha1
kind: Trigger
metadata:
  annotations:
    meta.upbound.io/example-id: devops/v1alpha1/trigger
  labels:
    testing.upbound.io/example-name: test_github_trigger
  name: test-github-trigger
  namespace: ${TARGET_NAMESPACE}
spec:
  forProvider:
    actions:
      - buildPipelineIdSelector:
          matchLabels:
            testing.upbound.io/example-name: test_build_pipeline
        filter:
          - events:
              - PUSH
            include:
              - baseRef: baseRef
                headRef: headRef
            triggerSource: GITHUB
        type: TRIGGER_BUILD_PIPELINE
    description: Github Trigger
    displayName: github-trigger
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_project
    triggerSource: GITHUB
  # providerConfig defaults to "ClusterProviderConfig"; set providerConfigRef to "ProviderConfig" to use namespaced providerConfig.
  providerConfigRef:
    name: default
    kind: ProviderConfig
