apiVersion: compute.oci.m.upbound.io/v1alpha1
kind: ComputeHostGroup
metadata:
  labels:
    testing.upbound.io/example-name: computehostgroup_label_1
  name: computehostgroup1
  namespace: ${TARGET_NAMESPACE}
spec:
  forProvider:
    availabilityDomain: ${AVAILABILITY_DOMAIN}
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    displayName: computehostgroup1
    isTargetedPlacementRequired: False
  # providerConfig defaults to "ClusterProviderConfig"; set providerConfigRef to "ProviderConfig" to use namespaced providerConfig.
  providerConfigRef:
    name: default
    kind: ProviderConfig
