apiVersion: compute.oci.m.upbound.io/v1alpha1
kind: InstanceConfiguration
metadata:
  labels:
    testing.upbound.io/example-name: instanceconfiguration_label_1
  name: instanceconfiguration1
  namespace: ${TARGET_NAMESPACE}
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    instanceDetails:
      - instanceType: "compute"
  # providerConfig defaults to "ClusterProviderConfig"; set providerConfigRef to "ProviderConfig" to use namespaced providerConfig.
  providerConfigRef:
    name: default
    kind: ProviderConfig
