apiVersion: streaming.oci.m.upbound.io/v1alpha1
kind: ConnectHarness
metadata:
  name: connectharness1
  labels:
    testing.upbound.io/example-name: connectharness_label_1
  namespace: ${TARGET_NAMESPACE}
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    name: "connectharness1"
  # providerConfig defaults to "ClusterProviderConfig"; set providerConfigRef to "ProviderConfig" to use namespaced providerConfig.
  providerConfigRef:
    name: default
    kind: ProviderConfig
