apiVersion: networkloadbalancer.oci.m.upbound.io/v1alpha1
kind: NetworkLoadBalancer
metadata:
  labels:
    testing.upbound.io/example-name: networkloadbalancer_label_1
  name: networkloadbalancer1
  namespace: ${TARGET_NAMESPACE}
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: subnet_label_1
    displayName: "networkloadbalancer1"
  # providerConfig defaults to "ClusterProviderConfig"; set providerConfigRef to "ProviderConfig" to use namespaced providerConfig.
  providerConfigRef:
    name: default
    kind: ProviderConfig
