
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: oci-events-v1alpha1-tests-template
spec:
  serviceAccountName: argo-workflow
  entrypoint: events-tests-workflow
  volumes:
    - name: git-repo
      persistentVolumeClaim:
        claimName: git-repo-pvc
  arguments:
    parameters:
    - name: compartment_ocid
    - name: function_image
    - name: create_application
      value: "true"
    - name: create_compartment
      value: "true"
    - name: create_function
      value: "true"
    - name: create_subnet
      value: "true"
    - name: create_vcn
      value: "true"
    - name: create_resources
      value: "true"
    - name: delete_resources
      value: "true"
  templates:
    - name: events-tests-workflow
      dag:
        tasks:
        - name: create-application
          templateRef:
            name: test-template
            template: create-resource
          when: "{{workflow.parameters.create_application}} == true"
          dependencies: [create-compartment, create-subnet]
          arguments:
            parameters:
              - name: resourceFile
                value: "examples/functions/v1alpha1/application.yaml"
        - name: create-compartment
          templateRef:
            name: test-template
            template: create-resource
          when: "{{workflow.parameters.create_compartment}} == true"
          arguments:
            parameters:
              - name: resourceFile
                value: "examples/identity/v1alpha1/compartment.yaml"
              - name: envVars
                value: "COMPARTMENT_OCID={{workflow.parameters.compartment_ocid}}"
        - name: create-function
          templateRef:
            name: test-template
            template: create-resource
          when: "{{workflow.parameters.create_function}} == true"
          dependencies: [create-application]
          arguments:
            parameters:
              - name: resourceFile
                value: "examples/functions/v1alpha1/function.yaml"
              - name: envVars
                value: "FUNCTION_IMAGE={{workflow.parameters.function_image}}"
        - name: create-subnet
          templateRef:
            name: test-template
            template: create-resource
          when: "{{workflow.parameters.create_subnet}} == true"
          dependencies: [create-compartment, create-vcn]
          arguments:
            parameters:
              - name: resourceFile
                value: "examples/networking/v1alpha1/subnet.yaml"
        - name: create-vcn
          templateRef:
            name: test-template
            template: create-resource
          when: "{{workflow.parameters.create_vcn}} == true"
          dependencies: [create-compartment]
          arguments:
            parameters:
              - name: resourceFile
                value: "examples/networking/v1alpha1/vcn.yaml"
        - name: create-rule
          templateRef:
            name: test-template
            template: create-resource
          when: "{{workflow.parameters.create_resources}} == true"
          dependencies: [create-compartment, create-function]
          arguments:
            parameters:
              - name: resourceFile
                value: "examples/events/v1alpha1/rule.yaml"
        - name: delete-rule
          templateRef:
            name: test-template
            template: delete-resource
          when: "{{workflow.parameters.delete_resources}} == true"
          dependencies: ["create-rule"]
          arguments:
            parameters:
              - name: resourceKind
                value: "{{tasks.create-rule.outputs.parameters.resourceKind}}"
              - name: resourceName
                value: "{{tasks.create-rule.outputs.parameters.resourceName}}"
              - name: resourceGroup
                value: "{{tasks.create-rule.outputs.parameters.resourceGroup}}"
