apiVersion: healthchecks.oci.m.upbound.io/v1alpha1
kind: HttpProbe
metadata:
  labels:
    testing.upbound.io/example-name: httpprobe_label_1
  name: httpprobe1
  namespace: ${TARGET_NAMESPACE}
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    protocol: HTTPS
    targets:
      - www.example.com
  # providerConfig defaults to "ClusterProviderConfig"; set providerConfigRef to "ProviderConfig" to use namespaced providerConfig.
  providerConfigRef:
    name: default
    kind: ProviderConfig
