apiVersion: healthchecks.oci.m.upbound.io/v1alpha1
kind: PingMonitor
metadata:
  labels:
    testing.upbound.io/example-name: pingmonitor_label_1
  name: pingmonitor1
  namespace: ${TARGET_NAMESPACE}
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    displayName: pingmonitor1
    intervalInSeconds: 30
    protocol: ICMP
    targets:
      - www.example.com
  # providerConfig defaults to "ClusterProviderConfig"; set providerConfigRef to "ProviderConfig" to use namespaced providerConfig.
  providerConfigRef:
    name: default
    kind: ProviderConfig
