apiVersion: stackmonitoring.oci.m.upbound.io/v1alpha1
kind: MaintenanceWindowsStop
metadata:
  annotations:
    meta.upbound.io/example-id: stackmonitoring/v1alpha1/maintenancewindowsstop
  labels:
    testing.upbound.io/example-name: test_maintenance_windows_stop
  name: test-maintenance-windows-stop
  namespace: ${TARGET_NAMESPACE}
spec:
  forProvider:
    maintenanceWindowId: ${var.maintenance_window_id}
  # providerConfig defaults to "ClusterProviderConfig"; set providerConfigRef to "ProviderConfig" to use namespaced providerConfig.
  providerConfigRef:
    name: default
    kind: ProviderConfig
