apiVersion: email.oci.m.upbound.io/v1alpha1
kind: Dkim
metadata:
  labels:
    testing.upbound.io/example-name: dkim_label_1
  name: dkim1
  namespace: ${TARGET_NAMESPACE}
spec:
  forProvider:
    emailDomainIdSelector:
      matchLabels:
        testing.upbound.io/example-name: emaildomain_label_1
  # providerConfig defaults to "ClusterProviderConfig"; set providerConfigRef to "ProviderConfig" to use namespaced providerConfig.
  providerConfigRef:
    name: default
    kind: ProviderConfig
