apiVersion: email.oci.m.upbound.io/v1alpha1
kind: Suppression
metadata:
  labels:
    testing.upbound.io/example-name: suppression_label_1
  name: suppression1
  namespace: ${TARGET_NAMESPACE}
spec:
  forProvider:
    compartmentId: ${TENANCY_OCID}
    emailAddress: emailsuppression1@email.dummydomain.com
  # providerConfig defaults to "ClusterProviderConfig"; set providerConfigRef to "ProviderConfig" to use namespaced providerConfig.
  providerConfigRef:
    name: default
    kind: ProviderConfig
