apiVersion: dns.oci.m.upbound.io/v1alpha1
kind: Rrset
metadata:
  labels:
    testing.upbound.io/example-name: rrset_label_1
  name: rrset1
  namespace: ${TARGET_NAMESPACE}
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    domain: rrset1.zone1.oci-dns1
    rtype: TXT
    zoneNameOrId: zone1.oci-dns1
  # providerConfig defaults to "ClusterProviderConfig"; set providerConfigRef to "ProviderConfig" to use namespaced providerConfig.
  providerConfigRef:
    name: default
    kind: ProviderConfig
