apiVersion: networking.oci.m.upbound.io/v1alpha1
kind: NatGateway
metadata:
  labels:
    testing.upbound.io/example-name: natgateway_label_1
  name: natgateway1
  namespace: ${TARGET_NAMESPACE}
spec:
  forProvider:
    blockTraffic: false
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    displayName: natgateway1
    vcnIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vcn_label_1
  # providerConfig defaults to "ClusterProviderConfig"; set providerConfigRef to "ProviderConfig" to use namespaced providerConfig.
  providerConfigRef:
    name: default
    kind: ProviderConfig
