apiVersion: networking.oci.m.upbound.io/v1alpha1
kind: NetworkSecurityGroup
metadata:
  labels:
    testing.upbound.io/example-name: networksecuritygroup_label_1
  name: networksecuritygroup1
  namespace: ${TARGET_NAMESPACE}
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    displayName: networksecuritygroup1
    vcnIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vcn_label_1
  # providerConfig defaults to "ClusterProviderConfig"; set providerConfigRef to "ProviderConfig" to use namespaced providerConfig.
  providerConfigRef:
    name: default
    kind: ProviderConfig
