apiVersion: datasafe.oci.m.upbound.io/v1alpha1
kind: Alert
metadata:
  annotations:
    meta.upbound.io/example-id: datasafe/v1alpha1/alert
  labels:
    testing.upbound.io/example-name: test_alert
  name: test-alert
  namespace: ${TARGET_NAMESPACE}
spec:
  forProvider:
    alertId: ${var.data_safe_alert_ocid}
    comment: ${var.alert_comment}
    freeformTags: ${var.alert_freeform_tags}
    status: ${var.alert_status}
  # providerConfig defaults to "ClusterProviderConfig"; set providerConfigRef to "ProviderConfig" to use namespaced providerConfig.
  providerConfigRef:
    name: default
    kind: ProviderConfig
