apiVersion: apigateway.oci.m.upbound.io/v1alpha1
kind: Subscriber
metadata:
  name: subscriber1
  labels:
    testing.upbound.io/example-name: subscriber_label_1
  namespace: ${TARGET_NAMESPACE}
spec:
  forProvider:
    displayName: subscriber1
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    usagePlans:
      - ${USAGEPLAN_OCID}
    clients:
      - name: "example-client"
        token: "generated_token_value"
  # providerConfig defaults to "ClusterProviderConfig"; set providerConfigRef to "ProviderConfig" to use namespaced providerConfig.
  providerConfigRef:
    name: default
    kind: ProviderConfig
