apiVersion: nosql.oci.m.upbound.io/v1alpha1
kind: Index
metadata:
  labels:
    testing.upbound.io/example-name: index_label_1
  name: index1
  namespace: ${TARGET_NAMESPACE}
spec:
  forProvider:
    keys:
      - columnName: column1
    name: index1
    tableNameOrIdSelector:
      matchLabels:
        testing.upbound.io/example-name: table_label_1
  # providerConfig defaults to "ClusterProviderConfig"; set providerConfigRef to "ProviderConfig" to use namespaced providerConfig.
  providerConfigRef:
    name: default
    kind: ProviderConfig
