apiVersion: appmgmt.oci.m.upbound.io/v1alpha1
kind: ControlMonitorPluginManagement
metadata:
  annotations:
    meta.upbound.io/example-id: appmgmt/v1alpha1/controlmonitorpluginmanagement
  labels:
    testing.upbound.io/example-name: test_monitor_plugin_management
  name: test-monitor-plugin-management
  namespace: ${TARGET_NAMESPACE}
spec:
  forProvider:
    monitoredInstanceId: ${var.monitored_instance_id}
  # providerConfig defaults to "ClusterProviderConfig"; set providerConfigRef to "ProviderConfig" to use namespaced providerConfig.
  providerConfigRef:
    name: default
    kind: ProviderConfig
