apiVersion: filestorage.oci.m.upbound.io/v1alpha1
kind: Export
metadata:
  name: export1
  labels:
    testing.upbound.io/example-name: export_label_1
  namespace: ${TARGET_NAMESPACE}
spec:
  forProvider:
    exportSetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: exportset_label_1
    fileSystemIdSelector:
      matchLabels:
        testing.upbound.io/example-name: filesystem_label_1
    path: "/examplemount"
  # providerConfig defaults to "ClusterProviderConfig"; set providerConfigRef to "ProviderConfig" to use namespaced providerConfig.
  providerConfigRef:
    name: default
    kind: ProviderConfig
