apiVersion: filestorage.oci.m.upbound.io/v1alpha1
kind: FileSystem
metadata:
  name: filesystem1
  labels:
    testing.upbound.io/example-name: filesystem_label_1
  namespace: ${TARGET_NAMESPACE}
spec:
  forProvider:
    displayName: filesystem1
    availabilityDomain: ${AVAILABILITY_DOMAIN}
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
  # providerConfig defaults to "ClusterProviderConfig"; set providerConfigRef to "ProviderConfig" to use namespaced providerConfig.
  providerConfigRef:
    name: default
    kind: ProviderConfig
