apiVersion: dataintegration.oci.m.upbound.io/v1alpha1
kind: Workspace
metadata:
  labels:
    testing.upbound.io/example-name: workspace_label_1
  name: workspace1
  namespace: ${TARGET_NAMESPACE}
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    description: "Test Data Integration Workspace"
    displayName: workspace1
  # providerConfig defaults to "ClusterProviderConfig"; set providerConfigRef to "ProviderConfig" to use namespaced providerConfig.
  providerConfigRef:
    name: default
    kind: ProviderConfig
