apiVersion: usageproxy.oci.m.upbound.io/v1alpha1
kind: SubscriptionRedeemableUser
metadata:
  annotations:
    meta.upbound.io/example-id: usageproxy/v1alpha1/subscriptionredeemableuser
  labels:
    testing.upbound.io/example-name: test_subscription_redeemable_user
  name: test-subscription-redeemable-user
  namespace: ${TARGET_NAMESPACE}
spec:
  forProvider:
    items:
      - emailId: ${var.email_id}
    subscriptionId: ${var.subscription_id}
    tenancyId: ${var.tenancy_ocid}
  # providerConfig defaults to "ClusterProviderConfig"; set providerConfigRef to "ProviderConfig" to use namespaced providerConfig.
  providerConfigRef:
    name: default
    kind: ProviderConfig
