apiVersion: identitydomains.oci.m.upbound.io/v1alpha1
kind: ApprovalWorkflow
metadata:
  annotations:
    meta.upbound.io/example-id: identitydomains/v1alpha1/approvalworkflow
  labels:
    testing.upbound.io/example-name: test_approval_workflow
  name: test-approval-workflow
  namespace: ${TARGET_NAMESPACE}
spec:
  forProvider:
    approvalWorkflowSteps:
      - typeSelector:
          matchLabels:
            testing.upbound.io/example-name: test_approval_workflow_approval_workflow_step
        valueSelector:
          matchLabels:
            testing.upbound.io/example-name: test_approval_workflow_approval_workflow_step
    attributeSets:
      - all
    attributes: ""
    authorization: ${var.approval_workflow_authorization}
    description: ${var.approval_workflow_description}
    idcsEndpoint: ${data.oci_identity_domain.test_domain.url}
    maxDuration:
      - unit: ${var.approval_workflow_max_duration_unit}
        value: ${var.approval_workflow_max_duration_value}
    name: ${var.approval_workflow_name}
    schemas:
      - urn:ietf:params:scim:schemas:oracle:idcs:ApprovalWorkflow
    tags:
      - key: ${var.approval_workflow_tags_key}
        value: ${var.approval_workflow_tags_value}
  # providerConfig defaults to "ClusterProviderConfig"; set providerConfigRef to "ProviderConfig" to use namespaced providerConfig.
  providerConfigRef:
    name: default
    kind: ProviderConfig
