apiVersion: servicecatalog.oci.m.upbound.io/v1alpha1
kind: ServiceCatalog
metadata:
  annotations:
    meta.upbound.io/example-id: servicecatalog/v1alpha1/servicecatalog
  labels:
    testing.upbound.io/example-name: test_service_catalog
  name: test-service-catalog
  namespace: ${TARGET_NAMESPACE}
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    displayName: ${var.service_catalog_display_name}
    freeformTags: ${var.service_catalog_freeform_tags}
  # providerConfig defaults to "ClusterProviderConfig"; set providerConfigRef to "ProviderConfig" to use namespaced providerConfig.
  providerConfigRef:
    name: default
    kind: ProviderConfig
