apiVersion: aivision.oci.m.upbound.io/v1alpha1
kind: StreamGroup
metadata:
  annotations:
    meta.upbound.io/example-id: aivision/v1alpha1/streamgroup
  labels:
    testing.upbound.io/example-name: test_stream_group
  name: test-stream-group
  namespace: ${TARGET_NAMESPACE}
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    streamSourceIdsRefs:
      - name: test_stream_source
  # providerConfig defaults to "ClusterProviderConfig"; set providerConfigRef to "ProviderConfig" to use namespaced providerConfig.
  providerConfigRef:
    name: default
    kind: ProviderConfig
